### ISSUE TITLE
Tela de detalhe da Publicação/Postagem

### ISSUE THREAD

**Issue by ronynogueiras** [pedlop/amigo-social#12]
Implementar a tela para visualização dos detalhes sobre uma publicação. 
Utilizar Activity 

- Layout (XML)
- Implementação (Java) 

Referências

[Picasso (Imagens)](http://square.github.io/picasso/)
[TextView](https://developer.android.com/reference/android/widget/TextView.html)
[ViewPager](https://developer.android.com/training/animation/screen-slide.html)

**Comment by pedlop** [comment]
- Tela implementada, [classe _DetalhePostagemActivity_](https://github.com/pedlop/amigo-social/blob/master/app/src/main/java/br/ufg/inf/amigosocial/DetalhePostagemActivity.java).
- Layout implementado, [xml _activity_detalhe_postagem_](https://github.com/pedlop/amigo-social/blob/master/app/src/main/res/layout/activity_detalhe_postagem.xml).
