### ISSUE TITLE
Discussão - Implementação Favoritos

### ISSUE THREAD

**Issue by ronynogueiras** [pedlop/amigo-social#14]
Analisando como seria realizada a implementação dos favoritos, percebi que há alguns detalhes que não foram planejados. Para que seja realizada a implementação do Salvar, Remover e Listar os Favoritos devemos escolher qual a forma que faremos isso, dentre os meios temos as seguintes opções:

- Salvar localmente (aparelho) utilizando SQLite 
- Salvar no servidor externo mas solicitando e-mail para listar os favoritos 
- Salvar no servidor externo mas utilizando o UUID do aparelho para listar os favoritos 

Gostaria de saber de vocês, @pedlop  e  @gabrielbo1 qual dessas opções seria mais conveniente para adicionar ao aplicativo.

Favor, responder nos comentários.

**Comment by pedlop** [comment]
Acredito que para esta versão, o ideal seria:
- Salvar localmente (aparelho) utilizando SQLite.
