### ISSUE TITLE
Criar tela para listagem dos Favoritos

### ISSUE THREAD

**Issue by ronynogueiras** [pedlop/amigo-social#6]
Realizar a implementação da tela para listagem dos favoritos.
Utilizar Fragment do support v4.

Referências
[Fragment](https://developer.android.com/reference/android/support/v4/app/Fragment.html)
[RecyclerView](https://developer.android.com/training/material/lists-cards.html?hl=pt-br)

**Comment by ronynogueiras** [comment]
@gabrielbo1 faltou adicionar o abrir a postagem. 

Você pode fazer isso adicionando um listener na lista, pode ser como este: 

https://github.com/pedlop/amigo-social/blob/master/app/src/main/java/br/ufg/inf/amigosocial/fragments/InicioFragment.java#L91

**Comment by pedlop** [comment]
Tela implementada, [java _FavoritosFragment_](https://github.com/pedlop/amigo-social/blob/master/app/src/main/java/br/ufg/inf/amigosocial/fragments/FavoritosFragment.java).
