### ISSUE TITLE
Criar layout para Favoritos

### ISSUE THREAD

**Issue by ronynogueiras** [pedlop/amigo-social#9]
Criar o layout (XML) para os favoritos. Deverá ser criado a layout base, em que deve ser colocado o RecyclerView (Lista). 

Deverá ser criado o layout para os item da lista. 

Referências
[RecyclerView](https://developer.android.com/training/material/lists-cards.html?hl=pt-br)

**Comment by pedlop** [comment]
Layout criado, [xml _fragment_favoritos_](https://github.com/pedlop/amigo-social/blob/master/app/src/main/res/layout/fragment_favoritos.xml).
